---
- name: Nginx Setup
  hosts: web
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy custom webpage
      copy:
        content: "<h1>Ansible on AWS EC2 Works!</h1>"
        dest: /var/www/html/index.html

